[build]
	publish = "_site"
	command = "npm run clean-site && npm run build-sass && npm run build"

# Content negotiation for home page
[[redirects]]
	from = "/"
	to = "/es/"
	status = 200
	conditions = {Language = ["es"]}

[[redirects]]
	from = "/"
	to = "/fr/"
	status = 200
	conditions = {Language = ["fr"]}

[[redirects]]
	from = "/"
	to = "/ja/"
	status = 200
	conditions = {Language = ["ja"]}

# Default content negotiation for home page
[[redirects]]
	from = "/"
	to = "/en/"
	status = 200

# Redirect for end-user’s browser preference override
[[redirects]]
	from = "/*"
	to = "/es/:splat"
	status = 302
	conditions = {Language = ["es"]}

[[redirects]]
	from = "/*"
	to = "/fr/:splat"
	status = 302
	conditions = {Language = ["fr"]}

[[redirects]]
	from = "/*"
	to = "/ja/:splat"
	status = 302
	conditions = {Language = ["ja"]}

# Default
[[redirects]]
	from = "/*"
	to = "/en/:splat"
	status = 302