backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "public/img" # Media files will be stored in the repo under public/img
public_folder: "/img" # The src attribute for uploaded media will begin with /img

i18n:
    structure: multiple_folders
    locales: [en, es, fr, ja]

collections:
    - name: "itinerary" # Used in routes, e.g., /admin/collections/blog
      label: "Itinerary" # Used in the UI
      folder: "/content/itineraries" # The path to the folder where the documents are stored
      i18n: true
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - {
                label: "Description",
                name: "description",
                widget: "string",
                i18n: true,
            }
          - {
                label: "Publish Date",
                name: "date",
                widget: "datetime",
                date_format: "YYYY-MM-DD",
                time_format: false,
                format: "YYYY-MM-DD",
                picker_utc: true,
                i18n: duplicate,
            }
          - {
                label: "Itinerary Date",
                name: "itineraryDate",
                widget: "datetime",
                date_format: "YYYY-MM-DD",
                time_format: false,
                format: "YYYY-MM-DD",
                picker_utc: true,
                i18n: duplicate,
            }
          - { label: "Body", name: "body", widget: "markdown", i18n: true }
